### ISSUE TITLE
Race condition with Logger

### ISSUE THREAD

**Issue by lthms** [riot-ml/riot#82]
Hi :wave: I am not sure this is really a bug, but consider the following snippet

```ocaml
open Riot

module App : Application.Intf = struct
  let start () =
    Logger.set_log_level (Some Debug);
    let pid =
      spawn @@ fun () -> Logger.info (fun f -> f "Hi %a" Pid.pp (self ()))
    in
    Ok pid
end

let () = start ~apps:[ (module Logger); (module App) ] ()
```

When executing this function, nothing happens. The program hangs without printing anything. I suspect this is because `App` starts more quickly than `Logger`, and as a consequence, the message is lost.

This can be verified quite easily: either add a call to `Riot.sleep` or make a recursive function printing the PID, and then the program behaves as expected.

Is there an idiomatic approach to wait for the `Logger` to be correctly initialized before doing anything else?

**Comment by leostera** [comment]
We don't, but I think we should make it so that the logger fully initializes itself before giving back control to the application boot sequence.

I can think of two things off the top of my head:
* make supervisors wait for children
* use a named process and await for it during Logger application start up

#### Make supervisors wait for children

Since the Logger application (logger_app.ml) is just a Supervisor (see: supervisor.ml), it think it could make sense to change how a Supervisor behaves so it only finished booting up after all its children have been initialized.

We should double-check the supervisor boot behavior on Erlang/Elixir and use that as a reference here. The main problem is that we can't guarantee a supervisor will boot quickly, so until that happens we potentially block a process instead of letting the supervisor initialize the children concurrently.

#### Explicit Logger lifecycle

Another option would be to make the Logger application use a `Logger_ready` message internally once it is ready to start logging things, so that a call to `Logger.start` makes sure to await for that message.

Code wise `Logger.start` would become something like:

```ocaml
type Message.t += Logger_ready

let start () = 
  let this = self () in
  let pid = initialize self in
  let selector msg = 
     match msg with
     | Logger_ready -> `select `ready
     | _ -> `skip
  in
  let `ready = receive ~selector () in
  Ok pid
```
